### PR TITLE
fix: trimmed headers for object result

### LINKED ISSUE #65: Header fields aren't trimmed when results returned as object
I ran into a bank that (stupidly) produced a CSV whose header fields had spaces around them. Since these fields were not trimmed, the object keys reflected these senseless spaces. For example:

```csv
Date, Description, Amount
2022-01-01,"My description",55
2022-05-01,"Another description",23.44
```

### Current State

Using the current code, the above produced the following results:

```javascript
console.log(CSV.parse(csvStr), { output: "objects" });
[
  {
    "Date": "2022-01-01",
    " Description": "My description",
    " Amount": "55",
  },
  {
    "Date": "2022-05-01",
    " Description": "Another description",
    " Amount": "23.44",
  },
]
```

### Expected Result

If we've asked for objects, we should trim header fields for those objects. However, we should NOT trim any row data, including the first row if we've requested tuples (rather than objects).

Using the above example, our expected return values should be the following:

```javascript
// Objects
console.log(CSV.parse(csvStr), { output: "objects" });
[
  {
    "Date": "2022-01-01",
    "Description": "My description",
    "Amount": "55",
  },
  {
    "Date": "2022-05-01",
    "Description": "Another description",
    "Amount": "23.44",
  },
]

// Tuples
console.log(CSV.parse(csvStr), { output: "tuples" });
[
  [ "Date", " Description", " Amount" ],
  [ "2022-01-01", "My description", "55" ],
  [ "2022-05-01", "Another description", "23.44" ],
]
```

### PR DESCRIPTION
**Pull request by kael-shipman**
Closes #65

@touv I know I didn't give you any time to comment on this issue, but I figured I'd submit this fix and if you find it controversial we can talk about it here. Please let me know!

### CODE REVIEW

**Comment by kael-shipman** [comment]
Separately, I noticed that I failed to run linting on my last PR. I didn't want to fill this PR up with a bunch of linting changes, but I'd be happy to submit a separate PR after this one to fix linting (and maybe make it automatic with husky?)

**Comment by touv** [comment]
Thank you, indeed, it is a good idea to clean the headers

**Comment by touv** [comment]
I just released v4.1.1 to include this fix

**Comment by kael-shipman** [comment]
Thank you for your prompt attention!

**Pull request merged**
